#!/usr/bin/env php

<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application('Hello Demo Tool', 0.1);

$app->add(new HelloCommand);

$app->run();
